### PR TITLE
RM-124258 Release over_react_codemod 2.2.0

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* Patch changes:
	* [CPLAT-15338 Alert Migrator](https://github.com/Workiva/over_react_codemod/pull/139)
	* [Fix wildcard to include branch names with slashes](https://github.com/Workiva/over_react_codemod/pull/141)
	* [INTL-2 Intl Migrator](https://github.com/Workiva/over_react_codemod/pull/142)
	* [Replace deprecated commands with new dart commands](https://github.com/Workiva/over_react_codemod/pull/143)
	* [Update references to the archived slack room #support-client-plat](https://github.com/Workiva/over_react_codemod/pull/144)
	* [INTL-4 Address follow up items](https://github.com/Workiva/over_react_codemod/pull/145)

Requested by: @matthewward-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_codemod/compare/2.1.1...Workiva:release_over_react_codemod_2.2.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_codemod/compare/2.1.1...2.2.0

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/6153708125028352/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6153708125028352/?pull_number=146&repo_name=Workiva%2Fover_react_codemod)

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by m-ward — APPROVED** [review]

**Review by matthewward-wf — APPROVED** [review]
+10

**Comment by matthewward-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
