### PR TITLE
FED-1143: Batch change to update consumers to new RMUI ESM bundle

### PR DESCRIPTION
**Pull request by annawatson-wk**
### Part 1 of 2: https://github.com/Workiva/sourcegraph-batch-changes/pull/197
Update references to RMUI JS bundles used in script tags to be the new ESM bundles:

- Update the paths preserving whether it's a dev or prod bundle:
`packages/react_material_ui/react-material-ui-development.umd.js` -> `packages/react_material_ui/js/react-material-ui.browser.dev.esm.js` &&
`packages/react_material_ui/react-material-ui.umd.js` -> `packages/react_material_ui/js/react-material-ui.browser.min.esm.js`
- Add a `type="module"` attribute to the script tag. Currently, if this is missing the script will probably fail.
- Look in both HTML files and Dart files

For usages that don't look like script tags:
- Do nothing, and we'll manually handle those

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author: 
    - [ ] the steps to run the codemod locally in a different repo: In the root directory of a different repo that you want to try to run the codemod on, `run dart pub global activate -s path ../over_react_codemod`. Then `run dart pub global run over_react_codemod:rmui_bundle_update` in that same repo and it should start showing you change diffs and ask if you want to accept them (I usually just accept all and then look at the diff at the end to see what it updated)

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Frontend Frameworks Design member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/over_react_codemod/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/over_react_codemod/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by brianphillips-wk — APPROVED** [review]
+1

Code's been previously tested (extensively)

**Comment by annawatson-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
