### PR TITLE
More tweaks/improvements to boilerplate codemod

### PR DESCRIPTION
**Pull request by greglittlefield-wf**
## Motivation
  
There were a handful of issues I ran into, either during last stretch of component migration or after the migration was finished, that could be fixed with some small changes.

## Changes
  
- Treat FIXMEs converted to TODOs the same as FIXMEs (and don't add new FIXMEs on top of them)
- Fix locally-generated semver reports not being readable due to not being nested inside an `{"exports": ...}` object
- Account for edge cases when Props were named `${componentName}ComponentProps`
- Ignore common mixins that are known to not implement lifecycle methods and thus shouldn't require necessitate migration:
    - FocusRestorer/FormControlApi/FormControlApiV2/TypedSnapshot
- Update minimum versions of over_react/over_react_test to include important bugfixes

#### Release Notes
(same as changes)

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

Please review: 

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author: 
        
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/over_react_codemod/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/over_react_codemod/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by sydneyjodon-wk — APPROVED** [review]
+10 

- [x] tests pass
- [x] verify boilerplate codemod reads semver_report.json with and without “exports” key
- [x] verify boilerplate codemod updates props classes that end in `Props` or `ComponentProps`
- [x] verify component2 codemod with `—no-partial-updates` flag still updates classes that mixin safe mixins
- [x] verify fixme comments aren't added if one already exists or was converted to a todo

**Comment by sydneyjodon-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
