### PR TITLE
INTL-71 Handle lib filepath exception

### PR DESCRIPTION
**Pull request by nicbiggs-wk**
## Motivation
  The codemod expects there to be a lib/src directory off of any folder in the given repo with a pubspec.yaml file, which is not always true. The Glob class does not handle filepaths that don't exist (at least until the newer version of Dart that we aren't using yet). This should be resolved.

## Changes
  Adds a try-catch to ignore when the lib directory doesn't exist

#### Release Notes
  Fix bug

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author: 
        
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/over_react_codemod/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/over_react_codemod/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by nicbiggs-wk** [comment]
@Workiva/intl

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by alanknight-wk — APPROVED** [review]

**Comment by alanknight-wk** [comment]
I started off making changes to this to just create the output directory ahead of time, so there was no question of whether `lib` existed or not, but then that would end up creating the directory even for things that we didn't need to make changes in (e.g. an app with just a `/web` directory. So I think this is probably better.

**Comment by alanknight-wk** [comment]
@Workiva/release-management-p

**Comment by alanknight-wk** [comment]
Argh. Accidentally made a change in this branch that's redundant with another. Now it will need approval by someone not me.

**Review by brendanburke-wk — APPROVED** [review]

**Comment by nicbiggs-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
