### PR TITLE
FED-1718 Callback ref null safety hint suggestor

### PR DESCRIPTION
**Pull request by sydneyjodon-wk**
## Motivation
  
In React, callback refs are called with the component instance upon render, and can be called with null when the component unmounts or when the component providing the ref rerenders.

For example instance:

// @dart=2.11
..ref = (FooComponent ref) {
  // ref could be null!
  _myRefVariable = ref;
}
As a result, callback refs should be typed as if the ref passed to them could be null.

The null safety migrator tool, however, seems to like to make these refs non-nullable.

To help with nullability inference during the null safety migration of over_react components, and to help prevent null errors afterwards, we need to develop codemods that adjust the typings of over_react callback refs.

## Changes
  
- Add a suggestor that changes the following cases:

1. For ref prop param types:
```diff
- (ButtonToolbar()..ref = (ButtonElement r) => ref = r)();
+ (ButtonToolbar()..ref = (ButtonElement /*?*/ r) => ref = r)();
```

2. For ref variable declarations:
```diff
- ButtonElement ref;
+ ButtonElement /*?*/ ref;
(ButtonToolbar()..ref = (r) => ref = r)();
```

3. For ref prop type casts:
```diff
- (ButtonToolbar()..ref = (r) => ref = r as ButtonElement)();
+ (ButtonToolbar()..ref = (r) => ref = r as ButtonElement /*?*/)();
```

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

Please review: 

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author: 
        
      - [ ] Run the codemod on some [consuming repos](https://sourcegraph.plat.workiva.net/search?q=context:global+%5C.%5C.ref%5Cs%3D%5Cs%5C%28+lang:dart+-repo:over_react+-repo:over_react_codemod&patternType=regexp&sm=1&groupBy=repo) using:
```
dart pub global activate https://github.com/Workiva/over_react_codemod.git --source=git --git-ref=callback-ref-null-safety-hint
dart pub global run over_react_codemod:null_safety_prep --yes-to-all
```
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Frontend Frameworks Design member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/over_react_codemod/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/over_react_codemod/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by sydneyjodon-wk** [comment]
@aaronlademann-wf yeahhh I was talking to Greg about that edge case because if the ref is referenced multiple times it will keep adding the nullability hint and we decided that it wouldn't be worth the effort to make the codemod be internally aware of the changes it was making to reduce duplication since it's an easy manual fix and I think the migrator tool should work regardless of comment duplication

**Review by aaronlademann-wf — APPROVED** [review]
+1 / +10

Ran the codemod locally in `admin_client`, `xbrl-module`, `w_table`, `graph_ui` and `doc_plat_client`. All expected changes look good, no unexpected changes or rtes while executing the codemod.

**Comment by sydneyjodon-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
